In [16]:
import pandas as pd

data = {"Name": ["Ali", "Sara"], "Age": [25, 30]}
df = pd.DataFrame(data)
df

   Name  Age
0   Ali   25
1  Sara   30

In [17]:
import pandas as pd
import numpy as np  

data = {
    "User": ["Ali", "Reza", "Sara", "Neda"],
    "Age": [25, np.nan, 30, 22],
    "City": ["Tehran", "Shiraz", np.nan, "Tehran"],
}
df = pd.DataFrame(data)

df

   User   Age    City
0   Ali  25.0  Tehran
1  Reza   NaN  Shiraz
2  Sara  30.0     NaN
3  Neda  22.0  Tehran

In [18]:
clean_dropped = df.dropna()

print("--- خروجی Dropna ---")
print(clean_dropped)
print("\n" + "=" * 30 + "\n")

clean_filled = df.copy()  
clean_filled["Age"] = clean_filled["Age"].fillna(0)
clean_filled["Age"] = clean_filled["Age"].astype(int)
clean_filled["City"] = clean_filled["City"].fillna("Unknown")

print("--- خروجی Fillna ---")
print(clean_filled)

--- خروجی Dropna ---
   User   Age    City
0   Ali  25.0  Tehran
3  Neda  22.0  Tehran

==============================

--- خروجی Fillna ---
   User  Age     City
0   Ali   25   Tehran
1  Reza    0   Shiraz
2  Sara   30  Unknown
3  Neda   22   Tehran

In [26]:
import pandas as pd
import numpy as np

data = {
    "User_ID": ["U1", "U2", "U3", "U4", "U5"],
    "Logins": [14, np.nan, 5, np.nan, 21],
    "Platform": ["App", "Web", np.nan, "App", np.nan],
}
df = pd.DataFrame(data)
df

  User_ID  Logins Platform
0      U1    14.0      App
1      U2     NaN      Web
2      U3     5.0      NaN
3      U4     NaN      App
4      U5    21.0      NaN

In [28]:
clean_df = df.copy()
clean_df["Logins"] = clean_df["Logins"].fillna(0)
clean_df["Logins"] = clean_df["Logins"].astype(int)
clean_df["Platform"] = clean_df["Platform"].fillna("Unknown")
clean_df

  User_ID  Logins Platform
0      U1      14      App
1      U2       0      Web
2      U3       5  Unknown
3      U4       0      App
4      U5      21  Unknown

In [29]:
import pandas as pd

data = {
    "User_ID": ["U1", "U1", "U2", "U3"],
    "Name": ["Ali", "Ali", "Reza", "Sara"],
    "Amount": [500, 500, 1200, 300],
}
df_dup = pd.DataFrame(data)

print("--- قبل از حذف تکراری‌ها ---")
print(df_dup)

clean_dup = df_dup.copy()
clean_dup = clean_dup.drop_duplicates()

print("\n--- بعد از حذف تکراری‌ها ---")
print(clean_dup)

--- قبل از حذف تکراری‌ها ---
  User_ID  Name  Amount
0      U1   Ali     500
1      U1   Ali     500
2      U2  Reza    1200
3      U3  Sara     300

--- بعد از حذف تکراری‌ها ---
  User_ID  Name  Amount
0      U1   Ali     500
2      U2  Reza    1200
3      U3  Sara     300

In [30]:
import pandas as pd

data = {
    "User_ID": ["U1", "U1", "U2"],
    "Amount": [500, 500, 1200],
    "Time": ["10:01", "10:02", "10:05"],  # کلیک دوم یک دقیقه بعد ثبت شده
}
df_real = pd.DataFrame(data)

print("--- تلاش برای حذف بدون Subset (اشتباه) ---")
print(df_real.drop_duplicates())

print("\n--- تلاش برای حذف با Subset (درست) ---")
clean_real = df_real.drop_duplicates(subset=["User_ID", "Amount"])
print(clean_real)

--- تلاش برای حذف بدون Subset (اشتباه) ---
  User_ID  Amount   Time
0      U1     500  10:01
1      U1     500  10:02
2      U2    1200  10:05

--- تلاش برای حذف با Subset (درست) ---
  User_ID  Amount   Time
0      U1     500  10:01
2      U2    1200  10:05

In [36]:
import pandas as pd

data = {
    "Order_ID": [101, 102, 103, 104, 105],
    "User_ID": ["U1", "U1", "U2", "U1", "U3"],
    "Product": ["Laptop", "Laptop", "Mouse", "Laptop", "Keyboard"],
    "Time": ["10:00:01", "10:00:03", "10:15:00", "15:30:00", "16:00:00"],
}
df_orders = pd.DataFrame(data)
clean_orders = df_orders.copy()
clean_orders = df_orders.drop_duplicates(subset=["User_ID", "Product"], keep="last")
clean_orders

   Order_ID User_ID   Product      Time
2       103      U2     Mouse  10:15:00
3       104      U1    Laptop  15:30:00
4       105      U3  Keyboard  16:00:00

In [37]:
import pandas as pd

data = {"Order_ID": [1, 2, 3], "Price": ["1,000$", "2,500$", "500$"]}
df_price = pd.DataFrame(data)

print("--- دیتای خام ---")
print(df_price)

clean_price = df_price.copy()

clean_price["Price"] = clean_price["Price"].str.replace("$", "")

clean_price["Price"] = clean_price["Price"].str.replace(",", "")

clean_price["Price"] = clean_price["Price"].astype(int)

print("\n--- دیتای تمیز شده برای محاسبات ریاضی ---")
print(clean_price)

--- دیتای خام ---
   Order_ID   Price
0         1  1,000$
1         2  2,500$
2         3    500$

--- دیتای تمیز شده برای محاسبات ریاضی ---
   Order_ID  Price
0         1   1000
1         2   2500
2         3    500

In [45]:
import pandas as pd

data = {
    "Campaign_ID": ["C1", "C2", "C3"],
    "Revenue": ["1,500,000 T", "850,000 T", "2,300,000 T"],
}
df_campaign = pd.DataFrame(data)
Clean_campaign = df_campaign.copy()
Clean_campaign["Revenue"] = Clean_campaign["Revenue"].str.replace(",", "").str.replace(" T", "")
Clean_campaign["Revenue"] = Clean_campaign["Revenue"].astype(int)
Clean_campaign

  Campaign_ID  Revenue
0          C1  1500000
1          C2   850000
2          C3  2300000

In [50]:
import pandas as pd

data = {
    "User_ID": ["U1", "U2", "U3"],
    "Join_Date": ["2023-10-01", "05/12/2023", "2023.08.15"],
}
df_dates = pd.DataFrame(data)

print("--- قبل از تبدیل (همه فقط متن هستند) ---")
print(df_dates)

clean_dates = df_dates.copy()

clean_dates["Join_Date"] = pd.to_datetime(clean_dates["Join_Date"], format="mixed")
print("\n--- بعد از استانداردسازی تاریخ ---")
print(clean_dates)

--- قبل از تبدیل (همه فقط متن هستند) ---
  User_ID   Join_Date
0      U1  2023-10-01
1      U2  05/12/2023
2      U3  2023.08.15

--- بعد از استانداردسازی تاریخ ---
  User_ID  Join_Date
0      U1 2023-10-01
1      U2 2023-05-12
2      U3 2023-08-15

In [61]:
import pandas as pd

data = {
    "User_ID": ["U1", "U2", "U3"],
    "Join_Date": ["2023-10-01", "2023/10/05", "2023-10-10"],
    "First_Purchase_Date": ["2023-10-05", "2023/10/20", "2023-10-11"],
}
df_users = pd.DataFrame(data)

clean_users = df_users.copy()
clean_users["Join_Date"] = pd.to_datetime(clean_users["Join_Date"], format="mixed")
clean_users["First_Purchase_Date"] = pd.to_datetime(clean_users["First_Purchase_Date"], format="mixed")
clean_users
clean_users["Days_to_Purchase"] = (
    clean_users["First_Purchase_Date"] - clean_users["Join_Date"]
)
clean_users

  User_ID  Join_Date First_Purchase_Date Days_to_Purchase
0      U1 2023-10-01          2023-10-05           4 days
1      U2 2023-10-05          2023-10-20          15 days
2      U3 2023-10-10          2023-10-11           1 days

In [74]:
import pandas as pd
import numpy as np

data = {
    "Order_ID": [101, 102, 102, 103, 104],
    "User_ID": ["U1", "U2", "U2", "U3", "U4"],
    "Date": ["2023-05-01", "2023/05/05", "2023/05/05", "2023.05.10", "2023-05-15"],
    "Revenue": ["1,000$", "2,500$", "2,500$", np.nan, "500$"],
}
df_final = pd.DataFrame(data)
clean_final = df_final.copy()
clean_final = clean_final.drop_duplicates(subset=["Order_ID", "User_ID"])
clean_final["Revenue"] = clean_final["Revenue"].fillna("0")
clean_final["Revenue"] =(clean_final["Revenue"].str.replace("$", "").str.replace(",", "").astype(int))
clean_final["Date"]=pd.to_datetime(clean_final["Date"], format="mixed")
clean_final

   Order_ID User_ID       Date  Revenue
0       101      U1 2023-05-01     1000
1       102      U2 2023-05-05     2500
3       103      U3 2023-05-10        0
4       104      U4 2023-05-15      500

In [75]:
import pandas as pd

data = {
    "Order_ID": [101, 102, 103, 104],
    "User_ID": ["U1", "U2", "U3", "U4"],
    "Revenue": [1500, -500, 0, 3200],  # رکورد 102 منفی است، رکورد 103 صفر است
}
df_quality = pd.DataFrame(data)

print("--- دیتای اولیه (با مشکلات منطقی) ---")
print(df_quality)

clean_quality = df_quality.copy()

clean_quality = clean_quality[clean_quality["Revenue"] > 0]

print("\n--- دیتای نهایی (تأیید شده از نظر کیفیت) ---")
print(clean_quality)

--- دیتای اولیه (با مشکلات منطقی) ---
   Order_ID User_ID  Revenue
0       101      U1     1500
1       102      U2     -500
2       103      U3        0
3       104      U4     3200

--- دیتای نهایی (تأیید شده از نظر کیفیت) ---
   Order_ID User_ID  Revenue
0       101      U1     1500
3       104      U4     3200

In [76]:
git add .

SyntaxError: invalid syntax (2022332482.py, line 1)